name: SeuCreyssonSounds
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  audioplayers: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imagens/creyretro.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  #imagens  
    - assets/imagens/crey.png
    - assets/imagens/macarrao.png
    - assets/imagens/pausar.png
    - assets/imagens/parar.png
    - assets/imagens/executar.png
    - assets/imagens/creypose.gif
    - assets/imagens/creymic.png
    - assets/imagens/creyputo.png
    - assets/imagens/creycabeca.png
    - assets/imagens/creyassustado.png
    - assets/imagens/creyretro.png
    
    
  #audios

    - assets/audios/silencer.mp3
    - assets/audios/macarrao.mp3
    - assets/audios/ranqueada.mp3
    - assets/audios/fumou.mp3
    - assets/audios/boua.mp3
    - assets/audios/carregar.mp3
    - assets/audios/drogon.mp3
    - assets/audios/esse void jogando.mp3
    - assets/audios/q disses.mp3
    - assets/audios/um palhaço.mp3
    - assets/audios/vamos capinar o lote.mp3
    - assets/audios/num va acertar um hook.mp3
    - assets/audios/ultaocara.mp3
    - assets/audios/dont go.mp3
    - assets/audios/eita man.mp3
    - assets/audios/einstein.mp3
    - assets/audios/vc é legenda.mp3
    # - assets/audios/para de falar irmio.mp3  

    - assets/audios/conhece o 120.mp3  
    - assets/audios/adianta telar.mp3  
    - assets/audios/ai é um jogador.mp3  
    - assets/audios/canto da sereia.mp3 
  
    - assets/audios/cuato cara no mid.mp3   
    - assets/audios/intimando o falen.mp3 
    
    - assets/audios/jimbreal sinonimos.mp3   
    - assets/audios/kd os donate.mp3   
    - assets/audios/lancha lancha remix.mp3
    - assets/audios/lanchados.mp3
    - assets/audios/liga e fala alguma coisa.mp3
    - assets/audios/ligando na gvt.mp3


    - assets/audios/omni cara.mp3
  
    - assets/audios/q q isso valve.mp3
    - assets/audios/quem disse que eu vo jogar com vcs.mp3
    - assets/audios/sou tri campeao goiano.mp3
    - assets/audios/usa malevolence.mp3
    - assets/audios/varios tp no mid.mp3
    - assets/audios/vc é legenda.mp3
    - assets/audios/vc n sabe da uma rolada.mp3
    - assets/audios/vem roshan.mp3

    - assets/audios/bate papo uol.mp3
    - assets/audios/callate hijo de mil pultas.mp3
    - assets/audios/cheiro da bosta.mp3
    - assets/audios/como q esse cara ta correndo tanto.mp3
    - assets/audios/depressão da onde.mp3
    - assets/audios/eu que to zuando o jogo.mp3
    - assets/audios/eu sou o sniper.mp3
    - assets/audios/hr de vc dormir.mp3
    - assets/audios/lancha lancha gretchen.mp3
    - assets/audios/macarrao q poha de ban rapaz.mp3
    - assets/audios/maior controlador de unidades.mp3
    - assets/audios/me responde na pagina.mp3
    - assets/audios/nun da empale ai n.mp3
    - assets/audios/o mais lixo que eu ja vi.mp3
    - assets/audios/pqr q q se tirou o galo.mp3
    - assets/audios/pudg suporte.mp3
    - assets/audios/quem tem dó do mendigo.mp3
    - assets/audios/resumo do patch.mp3
    - assets/audios/desgraçado saiu do jogo.mp3
    - assets/audios/se tem q melhorar mt.mp3
    - assets/audios/seis n vao jogar mais cmg.mp3
    - assets/audios/soy lucas codorna.mp3
    - assets/audios/tu é horrivel de mais cara.mp3
    - assets/audios/ai é intelegente.mp3
    - assets/audios/depoimento aluno loucademia.mp3
    - assets/audios/e para de me ligar zbc.mp3
    - assets/audios/o jogo ja acabou seus inbecil.mp3
    - assets/audios/q troxa oq rapaz.mp3
    - assets/audios/vc é um sup 5 animal.mp3
    - assets/audios/direitos da loucademia.mp3 
    - assets/audios/seis demoraram pra achar game.mp3
    
    
    
   

    
    
   
    

  
   
   
    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
